@startuml usecase
left to right direction

package Démarrage {
    actor "Joueur" as player
    usecase "Menu options" as options
    usecase "Changer nom joueur" as name
    usecase "Activer/Désactiver le son" as sound
    usecase "Classement par difficulté" as leaderboard
    usecase "Choix difficulté" as difficulty
    usecase "Quitter" as leaveGame
    usecase "Jouer" as jouer
}
player --> name
player --> jouer
player --> difficulty
player --> leaveGame
player --> leaderboard
player --> options
options ..> sound: <<include>>

newpage 
left to right direction

package Jeu {
    actor "Joueur" as player
    usecase "Menu pause" as pause
    usecase "Menu options" as options
    usecase "Recommencer" as restart
    usecase "Quitter" as leave
    usecase "Continuer" as continue
    usecase "Déplacer le personnage" as play
    usecase "Activer/Désactiver le son" as sound
}

player --> play
player --> pause
pause ..> options: <<include>>
pause ..> continue: <<extends>>
pause ..> restart: <<extends>>
pause ..> leave: <<extends>>
options ..> sound: <<include>>

note left of pause
    Met le jeu en pause
end note

newpage
left to right direction

package GameOver {
    actor "Joueur" as player
    usecase "Recommencer" as restart
    usecase "Quitter" as leave
}

player --> restart
player --> leave
@enduml